P=main.out
OBJECTS=main.c queue.c queue.h singly_linked_list/sllist.c singly_linked_list/sllist.h
CFLAGS=-Wall -g -pedantic -ansi
LIBS=
CC=gcc

all:
	$(CC) $(CFLAGS) -o $(P) $(OBJECTS) $(LIBS)

clean:
	rm -rf *.out
